name: Flask API CI/CD Pipeline

on:
  push:
    branches:
      
master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v2

      
name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1' # Use the Python version you need

      
name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      
name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      
name: Checkout code
      uses: actions/checkout@v2

      
name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: fares1300/gp_models:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      
name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
